### ISSUE TITLE
What about gtk theming in stack header ???

### ISSUE THREAD

**Issue by athamour1** [pop-os/shell#1202]
Basically the title, it's a feature request or general discussion about that, how about the stack's header in pop shell is themed from gtk shell theme ???

**Comment by birneee** [comment]
> Supported style classes are:
> 
> * `pop-shell-tab`
> * `pop-shell-tab-active`
> * `pop-shell-tab-inactive`
> * `pop-shell-tab-urgent`

I tried to customize these by adding it to the `gtk-3.0/gtk.css` of the theme, but nothing changed.

**Comment by mmstick** [comment]
@birneee The header is provided by GNOME Shell Toolkit (`St`) rather than GTK. So it has to be part of the GNOME Shell theme.

**Comment by birneee** [comment]
@mmstick thanks for your fast reply

i added e.g. the following to the `gnome-shell/gnome-shell.css` of my theme
  ```css
.pop-shell-tab,
.pop-shell-tab-active,
.pop-shell-tab-urgent,
.pop-shell-tab-inactive { 
    background: #FF0000!important;
}
```
But still no effect
