### ISSUE TITLE
PopShell Wayland no option to hide title bar

### ISSUE THREAD

**Issue by MikeStutzzzz** [pop-os/shell#768]
**(1) Issue/Bug Description:**
when using wayland there is not an option to hide the title bar

**(2) Steps to reproduce (if you know):**

**(3) Expected behavior:**
option to hide the title bar

**(4) Distribution (run `cat /etc/os-release`):**
 NAME="Pop!_OS"
VERSION="20.10"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.10"
VERSION_ID="20.10"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=groovy
UBUNTU_CODENAME=groovy
LOGO=distributor-logo-pop-os

**(5) Gnome Shell version:**
GNOME 3.38.1 

**(6) Pop Shell version (run `apt policy pop-shell` or provide the latest commit if building locally):**
<!--
Use triple back ticks ```pop-shell:
  Installed: 1.0.0~1607112536~20.10~9e13d5d
  Candidate: 1.0.0~1607112536~20.10~9e13d5d
  Version table:
 *** 1.0.0~1607112536~20.10~9e13d5d 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu groovy/main amd64 Packages
       1001 http://ppa.launchpad.net/system76/pop/ubuntu groovy/main i386 Packages
        100 /var/lib/dpkg/status
``` to paste the apt policy pop-shell value, so it formats nicely
-->



**(7) Where was Pop Shell installed from:**
Built in


**(8) Monitor Setup (2 x 1080p, 4K, Primary(Horizontal), Secondary(Vertical), etc):**



**(9) Other Installed/Enabled Extensions:**



**(10) Other Notes:**

             /////////////                 
         /////////////////////            ----------- 
      ///////*767////////////////         OS: Pop!_OS 20.10 x86_64 
    //////7676767676*//////////////       Host: Gazelle gaze11 
   /////76767//7676767//////////////      Kernel: 5.8.0-7630-generic 
  /////767676///*76767///////////////     Uptime: 9 mins 
 ///////767676///76767.///7676*///////    Packages: 2301 (dpkg), 30 (flatpak) 
/////////767676//76767///767676////////   Shell: bash 5.0.17 
//////////76767676767////76767/////////   Resolution: 1920x1080 
///////////76767676//////7676//////////   DE: GNOME 3.38.1 
////////////,7676,///////767///////////   WM: Mutter 
/////////////*7676///////76////////////   WM Theme: Pop 
///////////////7676////////////////////   Theme: Pop-dark [GTK2/3] 
 ///////////////7676///767////////////    Icons: Pop [GTK2/3] 
  //////////////////////'////////////     Terminal: tilix 
   //////.7676767676767676767,//////      CPU: Intel i7-6700HQ (8) @ 3.500GHz 
    /////767676767676767676767/////       GPU: Intel HD Graphics 530 
      ///////////////////////////         Memory: 3114MiB / 32000MiB 
         /////////////////////
             /////////////

**Comment by mmstick** [comment]
It's because in X, the display manager manages window decorations, but in Wayland, windows are responsible for managing their own window decorations. Client-side decorations (Wayland) versus server-side decorations (X11). This feature cannot be implemented in Wayland.

**Comment by MikeStutzzzz** [comment]
Interesting thanks, I was using Unite with hide tittle bar to accomplish this on wayland just thought it was missing from pop shell I guess the way the two extensions handles hiding the tittle bar is different. Thanks for the answer

**Comment by ryleu** [comment]
> Interesting thanks, I was using Unite with hide tittle bar to accomplish this on wayland just thought it was missing from pop shell I guess the way the two extensions handles hiding the tittle bar is different. Thanks for the answer

Per that extension's page:

> Since version 2 applications on wayland with client side decorations are supported using CSS.

So it's basically a hack. I wouldn't mind having that hack as an option in pop-os/shell, though it might take a bit of work. I'll look into making a PR after finals are over.

Edit: this seems to be the commit where it was added: https://github.com/hardpixel/unite-shell/commit/38ba6eea5c63bd3bcc1fd44258a6768024a4028e

**Comment by io12** [comment]
This seems to work when added to `$XDG_CONFIG/gtk-3.0/gtk.css`:

```css
/* Hide title bar */
/* Modified from https://github.com/hardpixel/unite-shell/blob/ec0a43fa5af157b53a24be3709f063bb14568a77/unite%40hardpixel.eu/styles/gtk3/buttons-right/maximized.css */
headerbar:not(.selection-mode),
.titlebar:not(.selection-mode),
headerbar > headerbar:not(.selection-mode),
.titlebar > .titlebar:not(.selection-mode),
.titlebar > stack > headerbar:not(.selection-mode),
headerbar:last-child:not(.selection-mode),
.titlebar:last-child:not(.selection-mode),
.windowhandle:not(.selection-mode) {
    padding-right: 0;
}
headerbar > box.right,
.titlebar > box.right {
    margin: 0 -200px 0 0;
    opacity: 0;
}
.titlebar.default-decoration {
    margin: -200px 0 0;
    opacity: 0;
}
```
