### ISSUE TITLE
Add Suspend to the launcher

### ISSUE THREAD

**Issue by WatchMkr** [pop-os/shell#827]
Appears that all other session management is present except suspend.

```
apt-cache policy pop-shell
pop-shell:
  Installed: 1.1.0~1610483356~20.10~891525b
  Candidate: 1.1.0~1610483356~20.10~891525b
  ```
